name: community_tools_sharing
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  introduction_screen: ^4.0.0
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.2.0 
  google_maps_flutter: ^2.13.1
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_google_places_sdk: ^0.4.2+1
  google_mlkit_text_recognition: ^0.15.0
  supabase_flutter: ^2.10.3
  firebase_messaging: ^16.0.4
  path_provider: ^2.0.15 
  path: ^1.8.3 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
flutter_native_splash:
  color: "#ffffff"
  background_image: assets\splash.jpg
  android_gravity: center
  ios_content_mode: center
  android_12:
    image: assets\splash.jpg  
    color: "#ffffff"